wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.16
    start_time: 1723021621.205484
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.7.16
      5: 0.13.9
      8:
      - 3
      - 5
architecture:
  desc: null
  value: MLP
dataset:
  desc: null
  value: MNIST
epochs:
  desc: null
  value: 30
learning_rate:
  desc: null
  value: 0.01
